sudo: false
language: python
python:
  - "2.7"
install:
  - "pip install -r requirements/main.txt -r requirements/test.txt"
  - "pip install python-coveralls"
script: "py.test --cov=pyramid_avro"
after_success:
  - coveralls
