sudo: false
language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - "pip install -r requirements/main.txt -r requirements/test.txt"
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install -r avro>=1.7 --use-mirrors; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then pip install -r avro-python3>=1.7 --use-mirrors; fi
  - "pip install python-coveralls"
script: "py.test --cov=pyramid_avro"
after_success:
  - coveralls
